spring:
  datasource:
    url: jdbc:h2:mem:db_usuario       # Banco em memória (apaga ao parar a aplicação)
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update                # Pode ser create, create-drop ou update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console                # Acesso no navegador (http://localhost:8080/h2-console)



#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/db_usuario
#    username: postgres
#    password: 260698
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

#jwt:
#  secret: c9R0NybVYl8E73kBv6qZ1mPfHD2jF8zX
