spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_usuario
    username: postgres
    password: 260698
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#jwt:
#  secret: c9R0NybVYl8E73kBv6qZ1mPfHD2jF8zX
